"""Vectorized SHA-256 round primitives with explicit carry tracking.

Demonstration module: batch-evaluates the SHA-256 compression function with
NumPy uint32 arithmetic, and separately counts the carry-outs of each modular
addition. Synthetic inputs only; deterministic; validated against hashlib.
"""

from __future__ import annotations

import numpy as np

_K = np.array([
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
    0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
    0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
    0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
    0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
], dtype=np.uint32)

_H0 = np.array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
], dtype=np.uint32)


def rotr(x: np.ndarray, n: int) -> np.ndarray:
    """Rotate-right on uint32 arrays."""
    n %= 32
    if n == 0:
        return x.copy()
    return ((x >> np.uint32(n)) | (x << np.uint32(32 - n))).astype(np.uint32)


def add_with_carry(a: np.ndarray, b: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Modular uint32 addition plus its carry-out (0 or 1) per lane."""
    s = (a + b).astype(np.uint32)
    carry = (s < a).astype(np.uint32)
    return s, carry


def _small_sigma0(x): return rotr(x, 7) ^ rotr(x, 18) ^ (x >> np.uint32(3))
def _small_sigma1(x): return rotr(x, 17) ^ rotr(x, 19) ^ (x >> np.uint32(10))
def _big_sigma0(x): return rotr(x, 2) ^ rotr(x, 13) ^ rotr(x, 22)
def _big_sigma1(x): return rotr(x, 6) ^ rotr(x, 11) ^ rotr(x, 25)
def _ch(e, f, g): return (e & f) ^ (~e & g)
def _maj(a, b, c): return (a & b) ^ (a & c) ^ (b & c)


def message_schedule(w: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Expand (N, 16) message words to (N, 64); also return carry counts.

    Returns (schedule, carries) where carries has shape (N,) and counts the
    carry-outs generated by the schedule's modular additions per message.
    """
    n = w.shape[0]
    full = np.zeros((n, 64), dtype=np.uint32)
    full[:, :16] = w
    carries = np.zeros(n, dtype=np.uint64)
    for t in range(16, 64):
        s0 = _small_sigma0(full[:, t - 15])
        s1 = _small_sigma1(full[:, t - 2])
        acc, c1 = add_with_carry(full[:, t - 16], s0)
        acc, c2 = add_with_carry(acc, full[:, t - 7])
        acc, c3 = add_with_carry(acc, s1)
        full[:, t] = acc
        carries += c1.astype(np.uint64) + c2 + c3
    return full, carries


def compress(state: np.ndarray, w: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """One SHA-256 compression over (N, 16) blocks from (N, 8) states.

    Returns (new_state, carry_counts): carry_counts (N,) uint64 tallies every
    modular-addition carry-out inside the 64 rounds and the final feed-forward.
    """
    sched, carries = message_schedule(w)
    a, b, c, d = (state[:, i].copy() for i in range(4))
    e, f, g, h = (state[:, i].copy() for i in range(4, 8))
    for t in range(64):
        t1, c1 = add_with_carry(h, _big_sigma1(e))
        t1, c2 = add_with_carry(t1, _ch(e, f, g))
        t1, c3 = add_with_carry(t1, _K[t])
        t1, c4 = add_with_carry(t1, sched[:, t])
        t2, c5 = add_with_carry(_big_sigma0(a), _maj(a, b, c))
        h, g, f = g, f, e
        e, c6 = add_with_carry(d, t1)
        d, c, b = c, b, a
        a, c7 = add_with_carry(t1, t2)
        for cx in (c1, c2, c3, c4, c5, c6, c7):
            carries += cx.astype(np.uint64)
    out = np.stack([a, b, c, d, e, f, g, h], axis=1)
    for i, v in enumerate((a, b, c, d, e, f, g, h)):
        out[:, i], cf = add_with_carry(state[:, i], v)
        carries += cf.astype(np.uint64)
    return out, carries


def sha256_single_block(messages: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """SHA-256 of (N, L) uint8 messages, L <= 55, via one padded block.

    Returns (digests, carry_counts): digests is (N, 32) uint8.
    """
    n, length = messages.shape
    if length > 55:
        raise ValueError("single-block demo supports messages up to 55 bytes")
    block = np.zeros((n, 64), dtype=np.uint8)
    block[:, :length] = messages
    block[:, length] = 0x80
    bitlen = np.uint64(length * 8)
    for i in range(8):
        block[:, 56 + i] = np.uint8((int(bitlen) >> (8 * (7 - i))) & 0xFF)
    w = block.reshape(n, 16, 4)
    words = (
        w[:, :, 0].astype(np.uint32) << 24
        | w[:, :, 1].astype(np.uint32) << 16
        | w[:, :, 2].astype(np.uint32) << 8
        | w[:, :, 3].astype(np.uint32)
    )
    state = np.broadcast_to(_H0, (n, 8)).copy()
    state, carries = compress(state, words)
    digest = np.zeros((n, 32), dtype=np.uint8)
    for i in range(8):
        digest[:, 4 * i] = (state[:, i] >> np.uint32(24)).astype(np.uint8)
        digest[:, 4 * i + 1] = (state[:, i] >> np.uint32(16)).astype(np.uint8)
        digest[:, 4 * i + 2] = (state[:, i] >> np.uint32(8)).astype(np.uint8)
        digest[:, 4 * i + 3] = state[:, i].astype(np.uint8)
    return digest, carries
